#define MAX_LINE_SEGMENTS 4000
#define MAX_RAY_QUERIES 4000
#define MAX_OCCLUSION_MESH_SIZE 1280
#define MAX_LIGHT_SOURCES 10

#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 900
#define SCREEN_ASPECT_RATIO ((float)SCREEN_WIDTH/SCREEN_HEIGHT)